### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by hardikpoojara** [rishiv3/s3-multiple-file-upload-angularJS#3]
Getting an error as AccessDenied during upload.
below are my settings 
`<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
  </CORSRule>
</CORSConfiguration>`

**Comment by mapkbalaji** [comment]
I too get the same error. It says FORBIDDEN.

**Comment by dgokcin** [comment]
has anyone ever solved this issue or do you have ab alternative method for doing the exact same thing? @hardikpoojara @mapkbalaji

**Comment by mirummar08** [comment]
@hardikpoo
@mapkbalaji
@dgokcin

give  s3 full read/ write access to role

**Comment by rishiv3** [comment]
if its AccessDenied or FORBIDDEN means you dont have write access on S3 bucket.
